# Generated by Django 4.0.4 on 2022-05-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_title_images_name_images_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['name']},
        ),
    ]
